### PR TITLE
fix tests, doctests and wasm build

### LINKED ISSUE #61: Broken wasm build due to std::process::id function call, is this a bug?
WASM build is broken in my project since upgrading wgpu-profiler. I guess it's been 'broken' since https://github.com/Wumpf/wgpu-profiler/pull/30. 

I'm not sure how you would like to proceed with this. On the one hand, I could probably find a way to never call wgpu-profiler functions from wasm builds. On the other hand, it was pretty nice being able to compile to web with no extra work required.

What do you think?

### PR DESCRIPTION
**Pull request by Davidster**
Resolves #61 

Let me know if you'd like me to separate the test fixes from the wasm fix, it's no issue.

### CODE REVIEW

File: tests/src/errors.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ fn invalid_pending_frame_count() {
 
 #[test]
 fn end_frame_unclosed_query() {
-    let (_, device, _) = create_device(wgpu::Features::TIMESTAMP_QUERY).unwrap();
+    let (_, device, _queue) = create_device(wgpu::Features::TIMESTAMP_QUERY).unwrap();
```
Comment (Davidster) [inline tests/src/errors.rs:21]: Believe it or not, the test was panicking without this change, since the queue was getting dropped before calling Device::create_command_encoder. I added a test to wgpu to check for this: 

https://github.com/gfx-rs/wgpu/pull/5211

Comment (Wumpf) [reply tests/src/errors.rs:21]: huh interesting. wonder why I didn't hit this before. Thanks for following up over on wgpu!

**Review by Wumpf — APPROVED** [review]
excellent, thank you!

No need for bureaucracy for this small change. Let's put it in as-is
Would be good to still add a check against the wasm target on ci, but we can do that later
